site_name: Project documentation
theme:
  name: material
  logo: assets/mainpost-logo.png
  favicon: assets/mainpost.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Getting Started: setup.md
  - Architecture: architecture.md
  - Data: data.md
  - Application: application.md
  - Backend: backend.md

extra_css:
  - custom/custom.css

copyright: |
  &copy; 2023 Simon Unterlugauer, Dominik Petermann, Jakob Weigand, Jenny Lindner
