site_name: Project Documentation

theme:
  name: material
  logo: assets/mainpost_logo.png
  favicon: assets/mainpost.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: grey
      accent: lime
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
      accent: purple

repo_url: https://github.com/UHPDome/backend_mainpost
repo_name: GitHub

nav:
  - Project Setup: 
    - Installation: projectSetup/installation.md
    - Docker Setup: projectSetup/dockerSetup.md 
  - Architecture: 
    - Overview: architecture/overview.md
    - Database: architecture/database.md 
    - Authentication Service: architecture/auth.md 
    - Frontend: architecture/frontend.md
    - Backend: architecture/backend.md
    - Dockerized Services: architecture/dockerizedArchitecture.md
  - Data Overview: 
    - Internal data: data/overview_data.md
    - Database model: data/databaseModel.md
  - Services:
    - Further services: externalServices/servicesWebApp.md
    - Services Modelling: externalServices/optuna.md
  - Web Application:
    - Landing Page: frontend/landingpage.md
    - Login: frontend/login.md
    - Dashboard: frontend/dashboard.md
    - Liefergebiete: frontend/liefergebiete.md
    - Mitarbeiter: frontend/mitarbeiter.md
    - Abwesenheitserfassung: frontend/abwesenheit.md
    - Historisches: frontend/historisches.md
    - Planung: frontend/planung.md
  - Backend:
    - Data Preparation: backend/data_prep.md
    - Models: backend/models.md
    - Performance: backend/performance.md
    - Prediction: backend/prediction.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tabbed

extra_css:
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  - customer/custom.css

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
  - "https://use.fontawesome.com/releases/v5.15.3/js/all.js"
  - customerjs/style.js

copyright: |
  &copy; 2023 Simon Unterlugauer, Dominik Petermann, Jakob Weigand, Jenny Lindner
